// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/todo.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3ce579ad8bb256f, []int{0}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetResponce struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Body                 string   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Done                 bool     `protobuf:"varint,4,opt,name=done,proto3" json:"done,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponce) Reset()         { *m = GetResponce{} }
func (m *GetResponce) String() string { return proto.CompactTextString(m) }
func (*GetResponce) ProtoMessage()    {}
func (*GetResponce) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3ce579ad8bb256f, []int{1}
}

func (m *GetResponce) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponce.Unmarshal(m, b)
}
func (m *GetResponce) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponce.Marshal(b, m, deterministic)
}
func (m *GetResponce) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponce.Merge(m, src)
}
func (m *GetResponce) XXX_Size() int {
	return xxx_messageInfo_GetResponce.Size(m)
}
func (m *GetResponce) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponce.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponce proto.InternalMessageInfo

func (m *GetResponce) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetResponce) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *GetResponce) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *GetResponce) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

func init() {
	proto.RegisterType((*GetRequest)(nil), "api.GetRequest")
	proto.RegisterType((*GetResponce)(nil), "api.GetResponce")
}

func init() { proto.RegisterFile("api/proto/todo.proto", fileDescriptor_b3ce579ad8bb256f) }

var fileDescriptor_b3ce579ad8bb256f = []byte{
	// 180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x49, 0x2c, 0xc8, 0xd4,
	0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x2f, 0xc9, 0x4f, 0xc9, 0xd7, 0x03, 0x33, 0x85, 0x98, 0x13,
	0x0b, 0x32, 0x95, 0x64, 0xb8, 0xb8, 0xdc, 0x53, 0x4b, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b,
	0x84, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x58, 0x83, 0x98, 0x32, 0x53,
	0x94, 0xa2, 0xb9, 0xb8, 0xc1, 0xb2, 0xc5, 0x05, 0xf9, 0x79, 0xc9, 0xa9, 0xe8, 0xd2, 0x42, 0x22,
	0x5c, 0xac, 0x25, 0x99, 0x25, 0x39, 0xa9, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x10, 0x8e,
	0x90, 0x10, 0x17, 0x4b, 0x52, 0x7e, 0x4a, 0xa5, 0x04, 0x33, 0x58, 0x10, 0xcc, 0x06, 0x89, 0xa5,
	0xe4, 0xe7, 0xa5, 0x4a, 0xb0, 0x28, 0x30, 0x6a, 0x70, 0x04, 0x81, 0xd9, 0x46, 0x46, 0x5c, 0x2c,
	0x21, 0xf9, 0x2e, 0xf9, 0x42, 0x5a, 0x5c, 0xcc, 0xee, 0xa9, 0x25, 0x42, 0xfc, 0x7a, 0x89, 0x05,
	0x99, 0x7a, 0x08, 0xc7, 0x48, 0x09, 0x20, 0x04, 0x20, 0xf6, 0x2b, 0x31, 0x38, 0x31, 0x47, 0x31,
	0xea, 0x25, 0xb1, 0x81, 0xdd, 0x6f, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xbf, 0x63, 0x4d, 0xda,
	0xd7, 0x00, 0x00, 0x00,
}
